export const DISCOVER_CARDS = [
    {
      id: 'habits',
      title: 'Habits',
      sessions: 20,
      colors: ['#C219CD', '#01A0A3'],
      route: 'Habits',
      icon: require('../assets/icons/habits.png'),
    },
    {
      id: 'therapy',
      title: 'Therapy',
      sessions: 20,
      colors: ['#52E5E7', '#130CB7'],
      route: 'Therapy',
      icon: require('../assets/icons/therapist.png'),
    },
    {
      id: 'relaxation',
      title: 'Relaxation',
      sessions: 1,
      colors: ['#79F1A4', '#0E5CAD'],
      route: 'BreathingStarts',
      icon: require('../assets/images/breathing1.png'),
    },
    {
      id: 'Games',
      title: 'Games',
      sessions: 4,
      colors: ['#1BAD7D', '#04D988'],
      route: 'Games',
      icon: require('../assets/images/game-cion.png'),
    },
    {
      id: 'affiramation',
      title: 'Affirmation',
      sessions: 20,
      colors: ['#F05F57', '#360940'],
      route: 'Affirmation',
      icon: require('../assets/icons/affirmation1.png'),
    },
    {
      id: 'Test',
      title: 'Test',
      sessions: 4,
      colors: ['#65FDF0', '#1D6FA3'],
      route: 'Test',
      icon: require('../assets/images/test.png'),
    },
    {
      id: 'nature',
      title: 'Nature',
      sessions: 6,
      colors: ['#C9778E', '#FCFF95'],
      route: 'NatureSounds',
      icon: require('../assets/images/nature.png'),
    },
    {
      id: 'news',
      title: 'News',
      sessions: 20,
      colors: ['#EE9AE5', '#5961F9'],
      route: 'News',
      icon: require('../assets/images/news.png'),
    },
    {
      id: 'meditation',
      title: 'Meditation',
      sessions: 10,
      colors: ['#B2B2B2', '#0D00FF'],
      route: 'Meditation',
      icon: require('../assets/images/meditation.png'),
    },
    {
      id: 'Diary',
      title: 'Diary',
      sessions: 1,
      colors: ['#F6459F', '#6E0F59'],
      route: 'Diary',
      icon: require('../assets/images/diary23.png'),
    },
  ];